name: "Conventional Commits"

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Check commits
        uses: webiny/action-conventional-commits@v1.3.1
